name: test suite

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-pyright
    - name: Install dependencies
      run: pip install -e . pyright pytest
    - name: Run pyright
      run: pyright --verifytypes anyio-http

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", pypy-3.11]
        include:
        - os: macos-latest
          python-version: "3.10"
        - os: macos-latest
          python-version: "3.13"
        - os: windows-latest
          python-version: "3.10"
        - os: windows-latest
          python-version: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Ensure pip >= v25.1
      run: python -m pip install "pip >= 25.1"
    - name: Install the project and its dependencies
      run: pip install --group test -e .
    - name: Generate coverage report
      run: coverage xml
    - name: Upload Coverage
      uses: coverallsapp/github-action@v2
      with:
        parallel: true
        file: coverage.xml

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Ensure pip >= v25.1
      run: python -m pip install "pip >= 25.1"
    - name: Install the project and its dependencies
      run: pip install --group doc -e .
    - name: Build documentation
      run: sphinx-build -W docs build/sphinx

  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
